### ISSUE TITLE
Polyfill not needed ? Also polyfill folder is not published on npm.

### ISSUE THREAD

**Issue by rook2pawn** [claudijo/level-tier#3]
hey @claudijo ! I think you can take out the polyfill on the first line for string repeat. However if you wanted to leave that in, I noticed that the polyfill folder wasn't included on npm so running it will give the user an error since the require will fail. Hope all is well, cheers!

**Comment by claudijo** [comment]
Thanks for pointing this out @rook2pawn! Package has been updated on NPM to include the polyfill directory.
