### ISSUE TITLE
discussion - techniques

### ISSUE THREAD

**Issue by rook2pawn** [claudijo/level-tier#4]
Hey @claudijo hope all is well. hoping to have a discussion on a few elements and some questions.

i'm using level-tier to namespace 

```js
  await db.put(
    leveltier(["game", "date", leveltier.now({ timestamp: now }), "id", id]),
    {
      uuid: id,
      ownerUUID: uuid,
      participants: [],
      createdDate: now,
    }
  );
```

to generate keys like the following  (.parse)
```
[
  'game',
  'date',
  '00000001640817757644',
  'id',
  '3241878f-8708-432a-8747-b102dce44a7f'
] // .parse
```

this allows me to do things like 
```js
      db.createReadStream({
        gte: leveltier.gte(["game", "date", leveltier.now({ timestamp: now })]),
        lte: leveltier.lte(["game"]),
      })
```
where now is 15 minutes ago so i can find games that are created in the last 15 minutes.

Then i realized I also wanted to find games by the id, but without knowing the date (or other parameters).

I started going down this direction to utilize **wildcards**

```js
const LOWER_BOUND = "\x00";
const UPPER_BOUND = "\uffff";

  const gte = leveltier.gte([
    "game",
    "date",
    LOWER_BOUND.repeat(20),
    "id",
    uuid,
  ]);
```

but I would like to know what you think I should do for an upper bound. I want to do this without creating additional "tables" as I believe this should be a straightforward operation - but adding an upper bound like this cuts off all results. I could use your perspective to help tackle this problem - and hopefully start creating a cookbook / illustrations on how to do different traditional db ideas in this paradigm.

(didn't work) 
```js
  const lte = leveltier.lte([
    "game",
    "date",
    UPPER_BOUND.repeat(20),
    "id",
    uuid,
  ]);
```

So given 
```
[
  'game',
  'date',
  '00000001640817757644',
  'id',
  '3241878f-8708-432a-8747-b102dce44a7f'
] 
```
how would you approach finding a GTE/LTE to get this entry without having to know the date value?

Thanks and Happy holidays!

**Comment by claudijo** [comment]
For your use case I would suggest to use an id that is time based and lexicographically sortable, for example ULID (https://github.com/ulid/javascript). That will enable time based range queries AND direct id queries (and you would probably not need to use name spaced keys at all).

However, If you need to query on arbitrary fields in your game object, creating an additional "table" would actually be the straight forward solution. That is, maintain an additional key space that maps some field value to a game object id. 

This is basically how database indexing work (https://en.wikipedia.org/wiki/Database_index) but in LevelDB you have to do it yourself :)

Let me know if you need any more clarification and if you don't mind, please send a link to your work. It would be interesting to see.
